version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Порт для доступа к фронтенду
    container_name: pc-gui
    environment:
      - VITE_APP_NAME=ИПП1
      - VITE_DOMAIN=localhost
      - VITE_API_PORT=5000
      - VITE_WS_PORT=8080

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
      # Порт для доступа к бэкенду
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb  # Указываем зависимость от сервиса mongodb
    container_name: pc-api


  mongodb:
    image: mongo
    ports:
      - "27017:27017"  # Порт MongoDB
    container_name: pc-db
    # Определяем volume для хранения данных MongoDB
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
