version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Порт для доступа к фронтенду

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Порт для доступа к бэкенду
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb  # Указываем зависимость от сервиса mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"  # Порт MongoDB

    # Определяем volume для хранения данных MongoDB
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
